const { contextBridge, ipcRenderer } = require("electron");

function subscribe(channel, callback) {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld("modelManager", {
  listModels: (query) => ipcRenderer.invoke("models:list", query),
  getModelsMeta: () => ipcRenderer.invoke("models:meta"),
  syncModels: () => ipcRenderer.invoke("models:sync"),
  toggleFavorite: (modelId) => ipcRenderer.invoke("models:toggle-favorite", modelId),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  updateSettings: (partial) => ipcRenderer.invoke("settings:update", partial),
  getStoragePath: () => ipcRenderer.invoke("storage:get-path"),
  listStorageDrives: () => ipcRenderer.invoke("storage:list-drives"),
  pickStoragePath: (defaultPath) => ipcRenderer.invoke("storage:pick-path", defaultPath),
  setStoragePath: (dirPath) => ipcRenderer.invoke("storage:set-path", dirPath),
  openStoragePath: (dirPath) => ipcRenderer.invoke("storage:open-path", dirPath),
  getDownloadQueue: () => ipcRenderer.invoke("download:queue"),
  startDownload: (modelId) => ipcRenderer.invoke("download:start", modelId),
  pauseDownload: (modelId) => ipcRenderer.invoke("download:pause", modelId),
  resumeDownload: (modelId) => ipcRenderer.invoke("download:resume", modelId),
  cancelDownload: (modelId) => ipcRenderer.invoke("download:cancel", modelId),
  getOllamaStatus: () => ipcRenderer.invoke("ollama:status"),
  startOllama: () => ipcRenderer.invoke("ollama:start"),
  openOllamaInstallPage: () => ipcRenderer.invoke("ollama:open-install"),
  listOllamaModels: () => ipcRenderer.invoke("ollama:list"),
  importToOllama: (modelId, options) =>
    ipcRenderer.invoke("ollama:import", { modelId, ...(options || {}) }),
  removeFromOllama: (modelId) => ipcRenderer.invoke("ollama:remove", modelId),
  deleteModel: (modelId) => ipcRenderer.invoke("models:delete", modelId),
  listPrompts: () => ipcRenderer.invoke("prompts:list"),
  toggleFavoritePrompt: (promptId) => ipcRenderer.invoke("prompts:toggle-favorite", promptId),
  listChatSessions: (modelId) => ipcRenderer.invoke("chat:sessions:list", modelId),
  searchChatSessions: (payload) => ipcRenderer.invoke("chat:sessions:search", payload),
  createChatSession: (payload) => ipcRenderer.invoke("chat:sessions:create", payload),
  getChatSession: (sessionId) => ipcRenderer.invoke("chat:sessions:get", sessionId),
  renameChatSession: (payload) => ipcRenderer.invoke("chat:sessions:rename", payload),
  deleteChatSession: (sessionId) => ipcRenderer.invoke("chat:sessions:delete", sessionId),
  exportChatSession: (sessionId) => ipcRenderer.invoke("chat:sessions:export", sessionId),
  setSessionPrompt: (sessionId, systemPrompt) =>
    ipcRenderer.invoke("chat:sessions:set-prompt", { sessionId, systemPrompt }),
  sendChatMessage: (payload) => ipcRenderer.invoke("chat:send", payload),
  stopChat: (sessionId) => ipcRenderer.invoke("chat:stop", sessionId),
  getAppVersion: () => ipcRenderer.invoke("app:version"),
  getCatalogInfo: () => ipcRenderer.invoke("models:catalog-info"),
  checkAppUpdate: () => ipcRenderer.invoke("app:check-update"),
  downloadAppUpdate: () => ipcRenderer.invoke("app:download-update"),
  installAppUpdate: () => ipcRenderer.invoke("app:install-update"),
  getDashboardStats: () => ipcRenderer.invoke("dashboard:stats"),
  openLogs: () => ipcRenderer.invoke("app:open-logs"),
  getPaiStatus: () => ipcRenderer.invoke("pai:get-status"),
  ensurePai: () => ipcRenderer.invoke("pai:ensure"),
  runPaiCommand: (payload) => ipcRenderer.invoke("pai:run", payload),
  runPaiDoctor: () => ipcRenderer.invoke("pai:doctor"),
  getComfyUiStatus: () => ipcRenderer.invoke("comfyui:status"),
  getComfyUiProgress: (payload) => ipcRenderer.invoke("comfyui:progress", payload),
  fetchPaiCatalog: () => ipcRenderer.invoke("pai:catalog"),
  fetchPaiPresets: () => ipcRenderer.invoke("pai:presets"),
  fetchPaiCapabilities: () => ipcRenderer.invoke("pai:capabilities"),
  runPaiCommandTracked: (payload) => ipcRenderer.invoke("pai:run-tracked", payload),
  scanLocalEnvironment: (options) => ipcRenderer.invoke("env:scan", options),
  applyComfyUiConfig: (payload) => ipcRenderer.invoke("env:apply-comfyui", payload),
  onDownloadProgress: (callback) => subscribe("download-progress", callback),
  onDownloadComplete: (callback) => subscribe("download-complete", callback),
  onDownloadError: (callback) => subscribe("download-error", callback),
  onOllamaImportProgress: (callback) => subscribe("ollama-import-progress", callback),
  onOllamaImportComplete: (callback) => subscribe("ollama-import-complete", callback),
  onOllamaImportError: (callback) => subscribe("ollama-import-error", callback),
  onOllamaRemoved: (callback) => subscribe("ollama-removed", callback),
  onOllamaChatChunk: (callback) => subscribe("ollama-chat-chunk", callback),
  onPaiRunProgress: (callback) => subscribe("pai-run-progress", callback),
  onAppUpdateAvailable: (callback) => subscribe("app-update-available", callback),
  onAppUpdateDownloaded: (callback) => subscribe("app-update-downloaded", callback),
  onAppUpdateProgress: (callback) => subscribe("app-update-progress", callback),
  onAppUpdateError: (callback) => subscribe("app-update-error", callback),
});
